### ISSUE TITLE
Permission Fails

### ISSUE THREAD

**Issue by MrErilio** [diecode/KillerMoney#28]
Hello, I noticed a little bug, indeed if I use the following configuration:
```

ZOMBIE:
     'world, world_nether, world_the_end':
         Money:
             Enabled: true
             Chance: 100%
             Value: 1 ? 2
             Permission: 'km.zombie.permission'
```

And that nobody has the permissions, nobody makes money, that's normal.
However, if I modify the Value, for:

```
ZOMBIE:
     'world, world_nether, world_the_end':
         Money:
             Enabled: true
             Chance: 100%
             Value: -1 ? -2
             Permission: 'km.zombie.permission'
```

At this point, permission is no longer needed, and everyone loses money whether they have permission or not.

It bothers me a lot so I wonder if it's a plugin worry, or me that is doing something wrong? Thank you.

Versions used: 4.3.2 on a Spigot 1.13.2
