### ISSUE TITLE
Issue with full inventories. 

### ISSUE THREAD

**Issue by codebycam** [diecode/KillerMoney#29]
**Server:** Paper 1.13.2 Build 588
**KillerMoney:** 4.3.2

I've checked over the configuration files and can't see anything for this. Players can't pick up the money if their inventory is full due to the money being an "item":

```
            Items:
                '1':
                    ItemStack:
                        ==: org.bukkit.inventory.ItemStack
                        type: GOLD_NUGGET
                    Random-amount: 1 ? 5
                    Chance: 100%
```

Cheers
